using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._PS.Expadition;

[GenerateTypedNameReferences]
public sealed partial class ExpaditionMenu : FancyWindow
{
    public event Action<BaseButton.ButtonEventArgs>? OnStartExpadition;

    public ExpaditionMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        StartExpaditionButton.OnPressed += args => OnStartExpadition?.Invoke(args);
    }
}
