# Base configuration preset used on all Prospect Sector servers.
# Loaded before server-specific config presets by configuration.

[game]
desc             = "Official English Prospect Sector servers."
lobbyenabled     = true
soft_max_players = 80
lobbyduration    = 300 # 5 minutes lobby timer
#panic_bunker.enabled = true
#panic_bunker.min_overall_minutes = 120
#panic_bunker.disable_with_admins = true
#panic_bunker.enable_without_admins = true
#panic_bunker.show_reason = true
#panic_bunker.custom_reason = "You have not played on a Prospect Sector server long enough to connect to this server."

# IPIntel stuff
#ipintel_enabled = true
#ipintel_contact_email = "telecommunications@spacestation14.com"
#ipintel_bad_rating = 0.99
#ipintel_alert_admin_warn_rating = 0.95

map_pool = "PSDefaultMapPool"

[infolinks]
bug_report = "https://github.com/Prospect-Sector/prospect-sector/issues/new/choose"
discord    = "https://discord.prospect-sector.space"
#forum      = "https://forum.prospect-sector.space"
github     = "https://github.com/Prospect-Sector/prospect-sector"
patreon    = "https://patreon.prospect-sector.space"
#website    = "https://prospect-sector.space"
#wiki       = "https://wiki.prospect-sector.space"
#appeal     = "https://discord.prospect-sector.space"

[server]
rules_file = "MRPRuleset"

[movement]
mob_pushing = false

[net]
max_connections = 1024

[vote]
restart_required_ratio = 0.7

[netres]
limit = 10.0

[admin]
see_own_notes = true
deadmin_on_join = true
new_player_threshold = 600
alert.min_players_sharing_connection = 2
allow_multi_server_play = false

[atmos]
max_explosion_range = 10

[gateway]
generator_enabled = false

[shuttle]
preload_grids = false

#[status]
#privacy_policy_link = "https://spacestation14.com/about/privacy/#game-server-privacy-policy"
#privacy_policy_identifier = "wizden"
#privacy_policy_version = "2025-01-19"
