- type: guideEntry
  id: PSSecurity
  name: guide-entry-security
  text: "/ServerInfo/_PS/Guidebook/Security/Security.xml"
  children:
  - PSForensics
  - PSDefusal
  - PSCriminalRecords
  - PSSpaceLaw

- type: guideEntry
  id: PSForensics
  name: guide-entry-forensics
  text: "/ServerInfo/_PS/Guidebook/Security/Forensics.xml"

- type: guideEntry
  id: PSDefusal
  name: guide-entry-defusal
  text: "/ServerInfo/_PS/Guidebook/Security/Defusal.xml"

- type: guideEntry
  id: PSCriminalRecords
  name: guide-entry-criminal-records
  text: "/ServerInfo/_PS/Guidebook/Security/CriminalRecords.xml"

- type: guideEntry
  id: PSSpaceLaw
  name: guide-entry-rules-space-law
  text: "/ServerInfo/_PS/Guidebook/ServerRules/SpaceLaw/SpaceLaw.xml"
  children:
  - PSSpaceLawCrimeList

- type: guideEntry
  id: PSSpaceLawCrimeList
  name: guide-entry-rules-sl-crime-list
  text: "/ServerInfo/_PS/Guidebook/ServerRules/SpaceLaw/SLCrimeList.xml"
