name: "Labels: PR"

on:
- pull_request_target

jobs:
  labeler:
    if: github.actor != 'ProspectBot' # Prospect: PJBot<ProspectBot
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
