name: "PR Changelog"
concurrency: commit_action
on:
  pull_request_target:
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHANGELOG_DIR: Resources/Changelog/Prospect.yml # Prospect: Changelog.yml<Prospect.yml
  PROSPECT_ADMIN_CHANGELOG_DIR: Resources/Changelog/ProspectAdmin.yml # Prospect: Prospect Admin changelog file
  PR_NUMBER: ${{ github.event.number }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: "${{ vars.CHANGELOG_BRANCH }}"

      - name: Setup Git
        run: |
          git config --global user.name "${{ vars.CHANGELOG_USER }}"
          git config --global user.email "${{ vars.CHANGELOG_EMAIL }}"
        shell: bash

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: |
          cd "Tools/_PS/changelog"
          npm install
        shell: bash
        continue-on-error: true

      - name: Generate Prospect Changelog
        run: |
          cd "Tools/_PS/changelog"
          export CHANGELOG_DIR="${{ env.CHANGELOG_DIR }}"
          node changelog.js
        shell: bash
        continue-on-error: true

      - name: Generate Prospect Admin Changelog
        run: |
          cd "Tools/_PS/changelog"
          export CHANGELOG_DIR="${{ env.PROSPECT_ADMIN_CHANGELOG_DIR }}"
          node changelog.js
        shell: bash
        continue-on-error: true

      - name: Commit Changelog
        run: |
          git add *.yml
          git commit -m "${{ vars.CHANGELOG_MESSAGE }} (#${{ env.PR_NUMBER }})"
          git push
        shell: bash
        continue-on-error: true
