using Content.Shared._PS.Terradrop;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class MiniMapCardControl : Control
{
    /// The map that this control represents
    public readonly TerradropMapPrototype MapProto;

    public MiniMapCardControl(TerradropMapPrototype mapProto, FormattedMessage description)
    {
        RobustXamlLoader.Load(this);
        MapDisplay.SetPrototype(mapProto.Icon);
        NameLabel.SetMessage(Loc.GetString(mapProto.Name));

        var tooltip = new Tooltip();
        tooltip.SetMessage(description);
        Main.TooltipSupplier = _ => tooltip;
        MapProto = mapProto;
    }
}
