using System.Linq;
using Content.Shared._PS.Terradrop;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;
    public Action<TerradropMapPrototype>? StartAction;

    public TerradropInfoPanel(TerradropMapPrototype proto, TerradropMapAvailability availability, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("terradrop.console");

        var terradrop = _ent.System<TerradropSystem>();

        NodeNameLabel.Text = Loc.GetString(proto.Name);
        NodeStatusLabel.Text = Loc.GetString(
            availability switch
            {
                TerradropMapAvailability.Unexplored => "terradrop-availability-unexplored",
                TerradropMapAvailability.Unavailable => "terradrop-availability-unavailable",
                TerradropMapAvailability.InProgress => "terradrop-availability-in-progress",
                TerradropMapAvailability.Explored => "terradrop-availability-explored",
                _ => "terradrop-availability-unknown"
            }
        );
        StartButton.Text = Loc.GetString(
            availability switch
            {
                TerradropMapAvailability.Unavailable => "terradrop-start-unavailable",
                TerradropMapAvailability.InProgress => "terradrop-start-in-progress",
                TerradropMapAvailability.Explored => "terradrop-start-explored",
                _ => "terradrop-start-generic"
            }
        );

        NodeTexture.SetPrototype(proto.Icon);

        InitializePrerequisites(proto, terradrop, sprite);
        InitializeMapUnlocks(proto, terradrop, sprite);

        StartButton.Disabled = availability == TerradropMapAvailability.Unavailable;

        // Replace the event handling method to use a simpler approach
        StartButton.OnPressed += _ =>
        {
            _sawmill.Debug($"Start button pressed for {proto.ID}");
            if (StartAction != null)
            {
                _sawmill.Debug($"Triggering StartAction for {proto.ID}");
                StartAction.Invoke(proto);
            }
            else
            {
                _sawmill.Error($"StartAction is null for {proto.ID}");
            }
        };

        _sawmill.Debug($"Created map panel: {proto.ID}, availability: {availability}, button disabled: {StartButton.Disabled}");
    }

    private void InitializePrerequisites(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        // required techs always visible, label in required techs
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }

        NoPrereqLabel.Visible = proto.MapPrerequisites.Count == 0;
        foreach (var mapId in proto.MapPrerequisites)
        {
            var tech = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(tech);
            RequiredTechContainer.AddChild(new MiniMapCardControl(tech, description));
        }
    }

    private void InitializeMapUnlocks(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var mapId in proto.MapUnlocks)
        {
            var map = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(map);
            UnlocksContainer.AddChild(new MiniMapCardControl(map, description));
        }
    }

}
