using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropInstanceListPopup : DefaultWindow
{
    /// <summary>
    /// Fired when an instance is selected. Passes the instance index.
    /// </summary>
    public Action<int>? InstanceSelected;

    public TerradropInstanceListPopup(List<string> instanceNames)
    {
        RobustXamlLoader.Load(this);

        for (var i = 0; i < instanceNames.Count; i++)
        {
            var index = i;
            var button = new Button
            {
                Text = instanceNames[i],
                HorizontalExpand = true,
            };
            button.OnPressed += _ =>
            {
                InstanceSelected?.Invoke(index);
                Close();
            };
            InstanceListContainer.AddChild(button);
        }
    }
}
