using System.Linq;
using Content.Shared._PS.Terradrop;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._PS.Terradrop;

[GenerateTypedNameReferences]
public sealed partial class TerradropInfoPanel : Control
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly ILogManager _logManager = default!;

    private ISawmill _sawmill = default!;

    /// <summary>
    /// Action invoked when starting a terradrop. Passes the prototype and selected level.
    /// </summary>
    public Action<TerradropMapPrototype, int>? StartAction;

    /// <summary>
    /// Action invoked when level is changed. Used to persist level selection.
    /// </summary>
    public Action<int>? LevelChanged;

    /// <summary>
    /// Action invoked when the disconnect button is pressed.
    /// </summary>
    public Action? DisconnectAction;

    /// <summary>
    /// Action invoked when an instance is selected for reconnection. Passes (mapId, instanceIndex).
    /// </summary>
    public Action<string, int>? ReconnectAction;

    private int _level;
    private readonly int _minLevel;
    private readonly TerradropMapPrototype _proto_;
    private readonly List<string>? _activeInstances;

    public TerradropInfoPanel(
        TerradropMapPrototype proto,
        TerradropMapAvailability availability,
        SpriteSystem sprite,
        int initialLevel = 0,
        List<string>? activeInstances = null)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sawmill = _logManager.GetSawmill("terradrop.console");
        _proto_ = proto;
        _activeInstances = activeInstances;

        var terradrop = _ent.System<TerradropSystem>();

        // Initialize level from prototype minimum and passed value
        _minLevel = proto.MinLevel;
        _level = Math.Max(initialLevel, _minLevel);

        NodeNameLabel.Text = Loc.GetString(proto.Name);
        NodeStatusLabel.Text = Loc.GetString(
            availability switch
            {
                TerradropMapAvailability.Unexplored => "terradrop-availability-unexplored",
                TerradropMapAvailability.Unavailable => "terradrop-availability-unavailable",
                TerradropMapAvailability.InProgress => "terradrop-availability-in-progress",
                TerradropMapAvailability.Explored => "terradrop-availability-explored",
                _ => "terradrop-availability-unknown"
            }
        );

        // Start button always says "Start New Instance" when in progress, otherwise normal text.
        StartButton.Text = Loc.GetString(
            availability switch
            {
                TerradropMapAvailability.Unavailable => "terradrop-start-unavailable",
                TerradropMapAvailability.InProgress => "terradrop-start-in-progress",
                TerradropMapAvailability.Explored => "terradrop-start-explored",
                _ => "terradrop-start-generic"
            }
        );

        NodeTexture.SetPrototype(proto.Icon);

        InitializePrerequisites(proto, terradrop, sprite);
        InitializeMapUnlocks(proto, terradrop, sprite);
        InitializeLevelControls();

        StartButton.Disabled = availability == TerradropMapAvailability.Unavailable;

        // Show disconnect/reconnect buttons only when instances exist.
        var hasInstances = activeInstances != null && activeInstances.Count > 0;
        DisconnectButton.Visible = hasInstances;
        ReconnectButton.Visible = hasInstances;

        // Start button sends prototype and level
        StartButton.OnPressed += _ =>
        {
            _sawmill.Debug($"Start button pressed for {proto.ID} at level {_level}");
            StartAction?.Invoke(proto, _level);
        };

        DisconnectButton.OnPressed += _ =>
        {
            DisconnectAction?.Invoke();
        };

        ReconnectButton.OnPressed += _ =>
        {
            if (_activeInstances == null || _activeInstances.Count == 0)
                return;

            // If only one instance, reconnect directly.
            if (_activeInstances.Count == 1)
            {
                ReconnectAction?.Invoke(_proto_.ID, 0);
                return;
            }

            // Multiple instances: show popup.
            var popup = new TerradropInstanceListPopup(_activeInstances);
            popup.InstanceSelected += index =>
            {
                ReconnectAction?.Invoke(_proto_.ID, index);
            };
            popup.OpenCentered();
        };

        _sawmill.Debug($"Created map panel: {proto.ID}, availability: {availability}, level: {_level}, button disabled: {StartButton.Disabled}");
    }

    private void InitializeLevelControls()
    {
        UpdateLevelDisplay();

        LevelMinusTenButton.OnPressed += _ => AdjustLevel(-10);
        LevelMinusButton.OnPressed += _ => AdjustLevel(-1);
        LevelPlusButton.OnPressed += _ => AdjustLevel(1);
        LevelPlusTenButton.OnPressed += _ => AdjustLevel(10);
    }

    private void AdjustLevel(int delta)
    {
        var newLevel = Math.Max(_minLevel, _level + delta);
        if (newLevel != _level)
        {
            _level = newLevel;
            UpdateLevelDisplay();
            LevelChanged?.Invoke(_level);
        }
    }

    private void UpdateLevelDisplay()
    {
        LevelLabel.Text = _level.ToString();

        // Show stat bonus info
        LevelBonusLabel.Text = _level > 0
            ? Loc.GetString("terradrop-level-bonus", ("bonus", _level))
            : "";

        // Disable minus buttons if at minimum
        LevelMinusButton.Disabled = _level <= _minLevel;
        LevelMinusTenButton.Disabled = _level <= _minLevel;
    }

    private void InitializePrerequisites(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        // required techs always visible, label in required techs
        foreach (var child in RequiredTechContainer.Children.ToList())
        {
            if (child != NoPrereqLabel)
                RequiredTechContainer.RemoveChild(child);
        }

        NoPrereqLabel.Visible = proto.MapPrerequisites.Count == 0;
        foreach (var mapId in proto.MapPrerequisites)
        {
            var tech = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(tech);
            RequiredTechContainer.AddChild(new MiniMapCardControl(tech, description));
        }
    }

    private void InitializeMapUnlocks(TerradropMapPrototype proto, TerradropSystem terradrop, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var mapId in proto.MapUnlocks)
        {
            var map = _proto.Index(mapId);
            var description = terradrop.GetMapDescription(map);
            UnlocksContainer.AddChild(new MiniMapCardControl(map, description));
        }
    }

}
